# Generated by Django 3.2.9 on 2022-01-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOTAL', models.IntegerField()),
                ('PAY_TYPE', models.CharField(max_length=30)),
                ('STATUS', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('CUST_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('CUST_NAME', models.CharField(max_length=50)),
                ('CUST_PH', models.CharField(max_length=10)),
                ('CUST_ADD', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='delivery_guy',
            fields=[
                ('DEL_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('DEL_NAME', models.CharField(max_length=50)),
                ('DEL_PH', models.CharField(max_length=10)),
                ('VEHI_NO', models.CharField(max_length=12)),
                ('SALARY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('IMG', models.ImageField(upload_to='')),
                ('DESC', models.TextField()),
                ('CUSINE', models.CharField(max_length=20)),
                ('TYPE', models.CharField(max_length=20)),
                ('NON_VEG', models.BooleanField(default=False)),
                ('RATE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('REST_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('REST_NAME', models.CharField(max_length=50)),
                ('REST_PH', models.CharField(max_length=10)),
                ('REST_ADD', models.TextField()),
                ('LOGO', models.ImageField(upload_to='')),
                ('COMMISSION', models.IntegerField(default=50)),
                ('NON_VEG', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUNTY', models.IntegerField()),
                ('PRICE', models.IntegerField()),
                ('BILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bill')),
                ('ITEM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='REST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurants'),
        ),
        migrations.AddField(
            model_name='bill',
            name='BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.delivery_guy'),
        ),
        migrations.AddField(
            model_name='bill',
            name='FROM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.restaurants'),
        ),
        migrations.AddField(
            model_name='bill',
            name='TO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customers'),
        ),
    ]
