# Generated by Django 3.2.9 on 2022-01-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='CUST_MAIL',
            field=models.EmailField(default='no_mail', max_length=254),
        ),
    ]
