# Generated by Django 3.2.9 on 2022-01-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customers_cust_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='CUST_GEN',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
