# Generated by Django 3.2.9 on 2022-01-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customers_cust_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='CUST_ADD',
        ),
        migrations.AddField(
            model_name='customers',
            name='CUST_CITY',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='CUST_DNUM',
            field=models.CharField(default='d', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='CUST_LOC',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='CUST_PIN',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='CUST_SNUM',
            field=models.CharField(default='00', max_length=5),
            preserve_default=False,
        ),
    ]
