# Generated by Django 3.2.9 on 2022-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220102_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_guy',
            name='DEL_GEN',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_guy',
            name='VEHI_TYPE',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
