# Generated by Django 3.2.9 on 2022-01-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220102_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='REST_ADD',
            field=models.CharField(max_length=30),
        ),
    ]
